### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by EasternGamer** [squeek502/WailaHarvestability#37] opened 2015-10-24 00:36 UTC
Hi I am having a problem which appears to be either from your mod or a combination of 2 mods including yours, what I seem to have come up with is through looking at my game log and crash report they all paint a strange picture ones has a tooltip issue with agricraft which maybe your waila tooltip bugging out but here are the 2 reports http://pastebin.com/90W1nxAS http://pastebin.com/c5sXhnC8 (Crash report second one) (First one is game log) If it is not a mod problem with yours could you point me in the direction of what it could be.

**Comment by itanshi** [comment] 2015-10-24 00:59
I had same issue, may be a corrupted chuink, but it triggers when i look at something http://pastebin.com/Pnq4cNCS

version 1.1.2

**Comment by squeek502** [comment] 2015-10-24 02:14
Not sure how it could be related to this mod. I don't do anything with networked entity properties. @MinecraftElite, you might want to [report this to AgriCraft](https://github.com/InfinityRaider/AgriCraft/issues), which seems to be causing the tooltip error. No clue what is causing the crash.

Try uninstalling Waila Harvestability and see if you can still reproduce the error/crash.

**Comment by itanshi** [comment] 2015-10-24 10:51
might even be an ender io thing with what i've been seeing lately. man these mods and their default configs.

**Comment by LemADEC** [comment] 2015-10-26 22:30
EntityTFNagaSegment['unknown'/326, l='MpServer', x=0.00, y=0.00, z=0.00],
=> that's a typical entityId overlap between your mods, nothing to do with Waila.

**Comment by squeek502** [comment] 2015-10-30 04:19
Closing this as it doesn't seem to be related to this mod. Re-open if you can confirm that this mod is causing it.

**Closed as completed by squeek502** 2015-10-30 04:19 UTC
Labels: bug, needs confirmation
