### ISSUE TITLE
Needs a updated version of WailaHarvestability for 1.16.5

### ISSUE THREAD

**Issue by IchigoGames** [squeek502/WailaHarvestability#82] opened 2021-04-25 16:50 UTC
WailaHarvestability-mc1.16.x-forge-1.1.14 is no longer compatible with version TConstruct-1.16.5-3.0.3.126 or forge 36.1.13
not sure if its the forge update or tinkers but it will show a msg saying that WailaHarvestability is for TConstruct no version list and then says what the installed version of TConstruct is was working before forge update tho so i think it mighty be a issue with forge

Minecraft 1.1.6.5
Forge 36.1.13
TConstruct-1.16.5-3.0.3.126
WailaHarvestability-mc1.16.x-forge-1.1.14

![image](https://user-images.githubusercontent.com/11888162/116001876-775dc200-a5bc-11eb-85a4-e0bbb5e8649b.png)

**Comment by GirafiStudios** [comment] 2021-04-25 17:37
Duplicate of https://github.com/squeek502/WailaHarvestability/issues/81

**Closed as completed by GirafiStudios** 2021-04-25 17:37 UTC

**Comment by squeek502** [comment] 2021-04-25 23:49
Will release a new version today.
