### ISSUE TITLE
GT 5.09.13 incorrect effective tool for ores

### ISSUE THREAD

**Issue by shifuren** [squeek502/WailaHarvestability#40] opened 2015-12-03 15:18 UTC
Something broke between GT 5.09.11 and 5.09.13, now all GT ores show shovel as effective harvest tool, thats incorrect. Though they are harvested as intended with pickaxe, so i guess it's display bug from your mod.
http://i.imgur.com/A07qFJq.jpg

**Comment by squeek502** [comment] 2015-12-03 21:57
Weird, will look into it.

**Comment by squeek502** [comment] 2015-12-12 05:24
Can't seem to reproduce this using GT 5.09.13 or 5.09.15.

![2015-12-11_21 21 45](https://cloud.githubusercontent.com/assets/2389051/11760382/7a378e9a-a04d-11e5-8607-9a851407a78e.png)
![2015-12-11_21 22 47](https://cloud.githubusercontent.com/assets/2389051/11760383/7a38bc02-a04d-11e5-85ae-f4892773b7c1.png)
![2015-12-11_21 23 02](https://cloud.githubusercontent.com/assets/2389051/11760384/7a39507c-a04d-11e5-9344-b4c32ad441b8.png)

**Comment by squeek502** [comment] 2015-12-12 05:35
@shifuren, if it's not too much trouble, could you test to make sure that with only GT + Waila + Waila Harvestability, the effective tool is still incorrect for you?

**Comment by Dream-Master** [comment] 2015-12-12 07:31
The Granite (Red and Black) have a higher Mining Level as Stone, Endstone and Netherrack so the Red/Black Granite ores maybe too?

**Comment by squeek502** [comment] 2016-06-30 06:57
Closing because I'm unable to reproduce the problem. Re-open if this is still an issue.

**Closed as completed by squeek502** 2016-06-30 06:57 UTC
Labels: bug, needs confirmation
